name: binance_auto_clicker
description: A professional auto-clicking tool for Binance coin launches with high-precision timing.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  permission_handler: ^11.3.1
  flutter_overlay_window: ^0.4.5
  wakelock_plus: ^1.2.5
  ntp: ^2.0.0
  vibration: ^1.8.4
  audioplayers: ^6.0.0
  flutter_local_notifications: ^17.2.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"